plugins {
    id 'com.android.application'
}

android {
    namespace 'com.loopcamera.loop20'
    compileSdk 34

    defaultConfig {
        applicationId "com.loopcamera.loop20"
        minSdk 29
        targetSdk 29
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        debug {
            enableV1Signing true
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            output.outputFileName = "CameraLoop10.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.annotation:annotation:1.8.2'

    constraints {
        implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
        implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24'
        implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
    }
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
    }
}
